### ISSUE TITLE
what do poses in poses.csv represent?

### ISSUE THREAD

**Issue by JzHuai0108** [AaltoVision/ADVIO#17]
So each row in pose.csv, (e.g., advio-01/ground-truth/pose.csv) is 
```
time[sec], tx, ty, tz, qw, qx, qy, qz
```
and the resulting transform can be computed by
```
T_XY = [R(qw, qx, qy, qz),  [tx, ty, tz]^T; 
              0, 0, 0,           1].
```
By T_XY, I mean, for a point expressed in coordinate frame Y, p_Y,  its coordinate in coordinate frame X, p_X can be computed by 
```
p_X = T_XY * p_Y.
```

I wonder how are the coordinate frames X and Y defined?
For ease of description, can you please explain the definitions of coordinate frames X and Y by relating to the below figure?
![image](https://user-images.githubusercontent.com/8062561/83629400-97fbe280-a5cc-11ea-86d7-d0671d48f14c.png)
The figure shows several coordinate frames, the camera frame(C), and the IMU frame(B), and a global frame(G) with z axis pointing to negative gravity.
I would deeply appreciate if you could describe say Y like
```
x axis of Y = x axis of C, y axis of Y = - z axis of C, z axis of Y = y axis of C, origin of Y = optical center of the camera on the iphone 6s.
```

**Comment by karnikram** [comment]
Hi,
I have the same issue and I've described whatever I could infer about the frame conventions here - #16. They seem to be working reasonably well for me

**Comment by JzHuai0108** [comment]
> Hi,
> I have the same issue and I've described whatever I could infer about the frame conventions here - #9. They seem to be working reasonably well for me

Hi @karnikram,

Thank you for your help. 
Do you forget to add the frame convention? I don't see any description about frame conventions at #9 or in this issue track.

**Comment by karnikram** [comment]
I meant #16, sorry!

**Comment by JzHuai0108** [comment]
Thank you, @karnikram. You confirmed my hypotheses about the body and world frame definitions.
