### ISSUE TITLE
Synchronization of accelerometer and gyroscope data？

### ISSUE THREAD

**Issue by thzt16** [AaltoVision/ADVIO#2]
Hi, Thanks for your excellent work!
In your paper, "Our sensor data is collected using a standard iPhone 6s device and contains the ground-truth pose trajectory and the raw synchronized data streams from the following sensors: RGB video camera, accelerometer, gyroscope, magnetometer, platform-provided geographic coordinates, and barometer."
But acturally, we find that the data stream from accelerometer and gyroscope are not synchronized. How to deal with it?
How can I run ROVIO on your dataset directly ?

**Comment by scortes48** [comment]
Yes, the data is saved separately for each sensor.
By synchronised we mean that all the timestamps are in the same time frame.

An example of interpolating the gyroscope data to align to the accelerometer timestamps is shown in 
https://github.com/AaltoVision/deep-speed-constrained-ins/blob/master/python/sync-data.py

From that structure it can be stored into a ROSbag with the format that ROVIO requires.
As shown in the API for ROS in python 
http://wiki.ros.org/rosbag/Code%20API#Python_API

I used the implementation in maplab.
https://github.com/ethz-asl/maplab

**Comment by zhukovv** [comment]
@scortes48 
Sorry, an additional question - have you got any good results with Maplab? I'm trying ADVIO with original Rovio, it's tracking but the pose seems not so correct, i.e. it constantly drifts upwards. I'm just wondering - is it an issue of my setup, e.g. gravitation is not subtracted because of the wrong axes alignment, or Maplab/Rovio is not capable to deal with smartphone data (not global shutter, not perfectly synchronized etc).

Thank you very much!

**Comment by K0stIa** [comment]
I have simiar issues with using maplab. @zhukovv  have you fixed it?

**Comment by scortes48** [comment]
Hello @K0stIa and @zhukovv 
A bug in the data has been recently discovered. I am writing parsing code that takes care of it.
The bug in question is in the timestamps of frames.csv and arkit.csv should start in 0. There is a small offset that desyncs the IMU and video data. 
The fix is to subtract the first timestamp from the whole time vector in those files.
Sorry for this.
I will publish a rosbag writer that should work in the data as is.

**Comment by K0stIa** [comment]
Hi @scortes48,

thanks for a reply! what about multiplying gyro by -1? have you done it already in this data?
If first frame's timestamp is 0.299746 and first imu measurement's timestamp is 0.0079320, is the timeshift 0.299746 - 0.0079320 = 0.291814 ?

**Comment by scortes48** [comment]
The data is as it is recorded by our (soon to be released) app. I have personally run maplab's ROVIOLI on the data and given the synchronisation fix it usually works in the easy sequences and kind off works on the harder ones.

The gyro and accelerometer timestamps are correct, is the video timestamp which is wrong. The pseudo code fix is:

t_frame = t_frame-t_frame[0]

where t_frame is the time vector of the video.

**Comment by K0stIa** [comment]
what about multiplying gyro by -1?

**Comment by K0stIa** [comment]
@scortes48 I have tried your suggestion on time correction and I am still failing with maplab.

**Comment by scortes48** [comment]
@K0stIa 
I pushed the scripts I use to write uncompressed rosbags.
They are the ones I use and work on my machine.
I will write more detailed instructions, but the code should be enough to check if you are doing the same thing.

**Comment by K0stIa** [comment]
@scortes48 

thanks a lot for your scipt! 

I have one more question though. Do you use default  rovioli config [link](https://github.com/ethz-asl/maplab/blob/master/applications/rovioli/share/rovio_default_config.info) ?

script to run maplab,

here it is
`#!/usr/bin/env bash
LOCALIZATION_MAP_OUTPUT=$1
ROSBAG=$2
ROVIO_CONFIG_DIR=$HOME/config/advio

NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/iphone-02.yaml"
IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/imu.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --datasource_type="rosbag" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST \
  --rovio_enable_frame_visualization=true \
  --detection_visualize_keypoints=true \
  --feature_tracker_publish_raw_images=true \
  --feature_tracker_visualize_keypoints=true \
  --feature_tracker_visualize_keypoints_individual_frames=true \
  --feature_tracker_visualize_keypoints=true \
  --feature_tracker_visualize_keypoint_matches=true
`

My iphone-02.yaml is exactly what you provide apart from the name change T_cam_imu -> T_B_C

imu.yaml
id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
hardware_id: imu0
sensor_type: IMU
sigmas:
  acc_noise_density: 4.8e-3
  acc_bias_random_walk_noise_density: 2.1e-4
  gyro_noise_density: 2.4e-3
  gyro_bias_random_walk_noise_density: 5.1e-5
saturation_accel_max_mps2: 150.0
saturation_gyro_max_radps: 7.5
gravity_magnitude_mps2: 9.81

I run advio-01, and raviloli flies over about half of dataset.. Could we sync up a maplab config? Which maplab's dataset you can fly by the end?

**Comment by K0stIa** [comment]
for sake of completeness, here is my modified iphone-2.yaml
`label: "Iphone - original_calibration"
id: 412eab8e4058621f7036b5e765dfe812
cameras:
- camera:
    label: cam0
    id: 54812562fa109c40fe90b29a59dd7798
    line-delay-nanoseconds: 0
    image_height: 1280
    image_width: 720
    type: pinhole
    intrinsics:
      cols: 1
      rows: 4
      data: [1077.2, 1079.3,362.145, 636.3873]
    distortion:
      type: radial-tangential  
      parameters:
        cols: 1
        rows: 4
        data: [0.0478, 0.0339, -0.00033,
    -0.00091]
  T_B_C:
      cols: 4
      rows: 4
      data: [0.9999763379093255, -0.004079205042965442, -0.005539287650170447, -0.008977668364731128,
        -0.004066386342107199, -0.9999890330121858, 0.0023234365646622014, 0.07557012320238939,
        -0.00554870467502187, -0.0023008567036498766, -0.9999819588046867, -0.005545773942541918,
         0.0, 0.0, 0.0, 1.0]    
`

**Comment by scortes48** [comment]
try to clip a few frames at the beginning, the initialization of the sequence (the start variable in the python script). ROVIOLI needs a good initialization to stay reasonable. You can get the harder sequences (like sequence 1) to work. 

I have the same values for the noise parameters and camera calibrations.
Good test sequences that usually work in current ROVIOLI:

- Sequence 15 is the easiest one.
- Sequence 13 is longer but still robust, the estimation drifts but does not diverge (in my machine)

**Comment by K0stIa** [comment]
For either seguence 13 or 15 I have to use iphone-03.yaml calibration file, hoverwer maplab says me that calibration is bad..

`F0405 14:09:04.156534  8784 rotation-quaternion-inl.h:115] Check failed: isValidRotationMatrix(matrix) 0000.999976 -0.00407921 -0.00553929
00.00406639 00-0.999989 00.00232344
0-0.0055487 -0.00230086 00-0.999982
`

**Comment by scortes48** [comment]
since the format is different you have to be careful when changing the matrix.
published format:
    T_cam_imu:
        cols: 4
        rows: 4
        data:
        - [0.9999763379093255, -0.004079205042965442, -0.005539287650170447, -0.008977668364731128]
        - [-0.004066386342107199, -0.9999890330121858, 0.0023234365646622014, 0.07557012320238939]
        - [-0.00554870467502187, -0.0023008567036498766, -0.9999819588046867, -0.005545773942541918]
        - [0.0, 0.0, 0.0, 1.0]

format for maplab


  T_B_C:
    cols: 4
    rows: 4
    data: [0.9999763379093255, -0.004079205042965442, -0.005539287650170447, -0.008977668364731128,
           -0.004066386342107199, -0.9999890330121858, 0.0023234365646622014, 0.07557012320238939,
           -0.00554870467502187, -0.0023008567036498766, -0.9999819588046867, -0.005545773942541918,
            0.0, 0.0, 0.0, 1.0]

**Comment by K0stIa** [comment]
Is T_B_C an R^T, -R^T × t of T_cam_imu ?

**Comment by scortes48** [comment]
I don't think so. I have not gone too deep into the meaning of the T_B_C and how  the reference frames are defined in ROVIOLI. So it very well may be. But, with this notation it runs on my machine. I will check it out.
Perhaps running ROVIO on the data-set is worth its own repo.  I will do some experiments.

**Comment by K0stIa** [comment]
Can you share this code too?

**Comment by K0stIa** [comment]
@scortes48 It'd nice as well if you give some comment on this [issue](https://github.com/ethz-asl/maplab/issues/117). How is it done in ADVIO datasets ?
