### ISSUE TITLE
Three questions about Calibration data

### ISSUE THREAD

**Issue by month612** [AaltoVision/ADVIO#5]
First of all, thanks to your contribution.I found that the intrinsics data in the README.md and iphone.yaml files are different. Which data should I choose ? Second, I have unified the time stamps of the accelerometer and the gyroscope , but can't run out of the trajectory which always have problems with inertial and visual align, I want to know which column the x, y, and z axes in the acc file and the gyr file belong to. Finally, I saw that you gave the iPhone IMU (approximate) additive biases, but can you give the specific values of white noise and random walk of IMU? Thank you very much.

**Comment by scortes48** [comment]
I have provided the IMU intrinsics. However keep in mind that these are usually artificially inflated for odometry systems. (see HKUST-Aerial-Robotics/VINS-Mobile)

the accelerometer and gyroscope data are in raw [x,y,z] order. The videos are portrait and thus the orientation matrix between the camera and the IMU has a 90 degree rotation (matrix provided).

The README files and their corresponding yaml files are listed now.

**Comment by karnikram** [comment]
> The videos are portrait and thus the orientation matrix between the camera and the IMU has an extra 90 degree rotation (matrix provided).

@scortes48 Can you please elaborate on this? The provided matrix seems to be a single 180 deg rotation about the IMU's x axis. Can we not use it for portrait images?
