### ISSUE TITLE
ARKIT logging App

### ISSUE THREAD

**Issue by mpkuse** [AaltoVision/ADVIO#7]
Is it possible to opensource the ARKIT iphone app so that others can collect their own data? 
This would be highly beneficial to the community. Hopefully this is feasible. Please do let me know. 
Thanks!

**Comment by scortes48** [comment]
Hi.
Thanks for your interest.
The data capture app will be made public (in the app store) soon. I will update this repo once it is. Stay posted

**Comment by Varvrar** [comment]
Hello!
I create app that makes iPhone/iPad datasets (similar to ADVIO). If you still need I can opensource it.

**Comment by JiamingSuen** [comment]
Hello @scortes48, I'm interested in the data capture app, is it already in the App Store? Where can I find it? Thanks!
